# Generated by Django 4.0.4 on 2022-05-15 10:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=user.models._generate_verification_code, max_length=6, validators=[django.core.validators.RegexValidator(message='123456 holatda kiriting', regex='^\\d{6}$')], verbose_name='Maxfiy kod')),
                ('contact', models.CharField(max_length=255, verbose_name='Aloqa raqami')),
                ('expire_at', models.DateTimeField(default=user.models._expire_at_default, verbose_name='Yaroqlilik muddati')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(help_text='998901234567 holatda kiriting', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='998901234567 holatda kiriting', regex='^(998)\\d{9}$')], verbose_name='Telefon raqami')),
                ('firstname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ismi:')),
                ('lastname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Familyasi:')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=user.models.user_avatar_file_path)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ro‘yxatdan o‘tgan sanasi')),
                ('is_superuser', models.BooleanField(default=False, help_text='Administrator huquqini beradi', verbose_name='Administratormi?')),
                ('is_staff', models.BooleanField(default=False, help_text='Admin qismiga kirish huquqini beradi.', verbose_name='Moderatormi?')),
                ('is_active', models.BooleanField(default=True, help_text='Saytga kirish huquqini beradi.', verbose_name='Aktivmi?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
